project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("textsummy.urls",namespace="summy")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

textsummy/urls.py
from django.urls import path
from textsummy.views import *

app_name = "textsummy"

urlpatterns = [
    path(""              ,HomePageView.as_view()         ,name="home" ),
    path("text-summary/" ,TextSummaryPageView.as_view()  ,name="text" ),
    path("files-summary/",FilesSummaryPageView.as_view()   ,name="files"  ),
    path("video-summary/",VideoSummaryPageView.as_view() ,name="video"),
    path("url-summary/"  ,UrlSummaryPageView.as_view()   ,name="url"  ),
]

templates/snippets/footer.html
{% load static %}
 <!-- Footer Start -->
<div class="container-fluid text-white mt-5 pt-5 px-sm-3 px-md-5" style="position: absolute;bottom:0;height:100px;background-color:#131313;">
</div>

templates/snippets/head.html
{% load static %}
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Free HTML Templates" name="keywords">
<meta content="Free HTML Templates" name="description">

<!-- Favicon -->
<link href="{% static '' %}img/favicon.ico" rel="icon">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"> 

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static '' %}lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static '' %}css/style.css" rel="stylesheet">

templates/snippets/header.html
{% load static %}
<!-- Navbar Start -->
<div class="container-fluid nav-bar p-0">
   <div class="container-lg p-0">
       <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
           <a href="/" class="navbar-brand">
               <h1 class="m-0 text-white display-4"><span class="text-primary"></span><span class="text-primary">S</span>ummary</h1>
           </a>
           <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
               <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
               <div class="navbar-nav ml-auto py-0">
                   <a href="/" class="nav-item nav-link active">Home</a>
                   <a href="{% url 'summy:text'  %}" class="nav-item nav-link">Text</a>
                   <a href="{% url 'summy:files'   %}" class="nav-item nav-link">files</a>
                   <a href="{% url 'summy:video' %}" class="nav-item nav-link">Video</a>
                   <a href="{% url 'summy:url'   %}" class="nav-item nav-link">Url</a>
               </div>
           </div>
       </nav>
   </div>
</div>
<!-- Navbar End -->

templates/snippets/header_pages.html
{% load static %}

<!-- Navbar Start -->
<div class="container-fluid nav-bar p-0 mb-5" style="top:0;position:fixed;background-color:#131313;">
    <div class="container-lg p-0">
        <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
            <a href="/" class="navbar-brand">
                <h1 class="m-0 text-white display-4"><span class="text-warning"></span><span class="text-warning">S</span>ummary</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav ml-auto py-0">
                    {% with request.resolver_match.url_name as url_name %}
                    <a href="/" class="nav-item nav-link {% if url_name == 'home'%} text-warning active {% else %} text-white {% endif %}">Home</a>
                    <a href="{% url 'summy:text'  %}" class="nav-item nav-link {% if url_name == 'text'%} text-warning active {% else %} text-white {% endif %}">Text</a>
                    <a href="{% url 'summy:files'   %}" class="nav-item nav-link {% if url_name == 'files'%} text-warning active {% else %} text-white {% endif %}">Files</a>
                    <a href="{% url 'summy:video' %}" class="nav-item nav-link {% if url_name == 'video'%} text-warning active {% else %} text-white {% endif %}">Video</a>
                    <a href="{% url 'summy:url'   %}" class="nav-item nav-link {% if url_name == 'url'%} text-warning active {% else %} text-white {% endif %}">Url</a>
                    {% endwith %}
                </div>
            </div>
        </nav>
    </div>
</div>
    <!-- Navbar End -->

templates/snippets/loader.html
{% load static %}

templates/snippets/scripts.html
{% load static %}
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static '' %}lib/easing/easing.min.js"></script>
<script src="{% static '' %}lib/waypoints/waypoints.min.js"></script>
<script src="{% static '' %}lib/counterup/counterup.min.js"></script>
<script src="{% static '' %}lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Contact Javascript File -->
<script src="{% static '' %}mail/jqBootstrapValidation.min.js"></script>
<script src="{% static '' %}mail/contact.js"></script>

<!-- Template Javascript -->
<script src="{% static '' %}js/main.js"></script>

templates/snippets/slider.html
{% load static %}
<!-- Carousel Start -->
<div class="container-fluid p-0 mb-5">
    <div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#header-carousel" data-slide-to="1"></li>
            <li data-target="#header-carousel" data-slide-to="2"></li>
            <li data-target="#header-carousel" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="img-fluid" src="{% static '' %}img/one.jpg" alt="Image" style="min-width:100%;height:100%">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Text</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="img-fluid" src="{% static '' %}img/carousel-2.jpg" alt="Image" style="min-width:100%;height:100%">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Video</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="img-fluid" src="{% static '' %}img/two.jpg" alt="Image" style="min-width:100%;height:100%">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Pdf</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="img-fluid" src="{% static '' %}img/carousel-3.jpg" alt="Image" style="min-width:100%;height:100%">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Voice</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->